view releases

diff --git a/.github/workflows/create_auto_deploy_maintenance_request.yml b/.github/workflows/create_auto_deploy_maintenance_request.yml
--- a/.github/workflows/create_auto_deploy_maintenance_request.yml
+++ b/.github/workflows/create_auto_deploy_maintenance_request.yml
@@ -8,18 +8,18 @@ env:
   snapshot_commit: 'Test Snapshot'
 
 jobs:
-  verify-version-update:
-    name: Confirm Snapshot
-    runs-on: ubuntu-latest
-    steps:
-      - name: MR Deployment Initialized
-        if: ${{ startsWith(env.commit_message, env.snapshot_commit) }}
-        run: echo  Detected ${{ env.snapshot_commit }} - beginning MR creation
-      - name: MR Deployment Abandoned
-        if: ${{ !startsWith(env.commit_message, env.snapshot_commit) }}
-        run: |
-          echo  Failed to locate MR initializer. Exiting...
-          exit 1;
+  # verify-version-update:
+  #   name: Confirm Snapshot
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: MR Deployment Initialized
+  #       if: ${{ startsWith(env.commit_message, env.snapshot_commit) }}
+  #       run: echo  Detected ${{ env.snapshot_commit }} - beginning MR creation
+  #     - name: MR Deployment Abandoned
+  #       if: ${{ !startsWith(env.commit_message, env.snapshot_commit) }}
+  #       run: |
+  #         echo  Failed to locate MR initializer. Exiting...
+  #         exit 1;
 
   pre_mr_checks_and_create:
     needs: verify-version-update
@@ -86,6 +86,7 @@ jobs:
           # Get the releases
           echo "Get the releases"
           gh api /repos/department-of-veterans-affairs/lighthouse-platform-backend/releases > releases.json
+          cat releases.json
           CURRENT_RELEASE_ID=`jq -r ".tag_name" releases.json`
           echo $CURRENT_RELEASE_ID
           PROPOSED_RELEASE_PRS=`jq -r ".[] | select(.id > $CURRENT_RELEASE_ID ) | \"- \" + .name + \"\"" releases.json | sed -E 's/(.*)\#([0-9]{1,})\)/\2/'`
