remove temporary prevent

diff --git a/.github/workflows/snapshot_update.yml b/.github/workflows/snapshot_update.yml
--- a/.github/workflows/snapshot_update.yml
+++ b/.github/workflows/snapshot_update.yml
@@ -13,13 +13,13 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Snapshot Commit Found
-        if: startsWith(env.commit_message, env.snapshot_commit)
+        # if: startsWith(env.commit_message, env.snapshot_commit)
         run: |
           echo "${{ env.snapshot_commit }} detected - deploying"
           echo 'Preparing to run Maintenance Request Creation...'
 
-      - name: Snapshot Commit Failed
-        if: ${{ !startsWith(env.commit_message, env.snapshot_commit) }}
-        run: |
-          echo 'Invalid commit message - exiting'
-          exit 1;
+      # - name: Snapshot Commit Failed
+      #   if: ${{ !startsWith(env.commit_message, env.snapshot_commit) }}
+      #   run: |
+      #     echo 'Invalid commit message - exiting'
+      #     exit 1;
